name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.16
      with:
        package-dir: python-package
      env:
        CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8,<3.12"
        CIBW_BUILD_FRONTEND: build
        CIBW_SKIP: pp* *musllinux*
        CIBW_ARCHS_WINDOWS: auto64
        CIBW_ARCHS_LINUX: auto64
        CIBW_ARCHS_MACOS: universal2

        CIBW_BEFORE_TEST: pip install onnxruntime
        CIBW_TEST_COMMAND: 'python -c "import insightface"'

    - uses: actions/upload-artifact@v4
      with:
        path: ./wheelhouse/*.whl
        name: insightface-${{ matrix.os }}

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist ./python-package

      - uses: actions/upload-artifact@v4
        with:
          name: insightface-sdist
          path: ./python-package/dist/*.tar.gz

  publish:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
